// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDPNsK3mW3hGeSh0TJ6lyPbjQ1YLxWTrA',
    appId: '1:758650158262:web:0b8846f5444049b71ffa17',
    messagingSenderId: '758650158262',
    projectId: 'uas-iot-7b202',
    authDomain: 'uas-iot-7b202.firebaseapp.com',
    storageBucket: 'uas-iot-7b202.firebasestorage.app',
    measurementId: 'G-19XL6CGG7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeVCwflRM0bWVFL5Kfgg2z9PX0E8rK4pQ',
    appId: '1:758650158262:android:1ef0aa40812284301ffa17',
    messagingSenderId: '758650158262',
    projectId: 'uas-iot-7b202',
    storageBucket: 'uas-iot-7b202.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG4sywJL8Ohz2wD8ep19-WBlf9hwIijII',
    appId: '1:758650158262:ios:8b636dc4fd6b3d451ffa17',
    messagingSenderId: '758650158262',
    projectId: 'uas-iot-7b202',
    storageBucket: 'uas-iot-7b202.firebasestorage.app',
    iosBundleId: 'com.example.uas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG4sywJL8Ohz2wD8ep19-WBlf9hwIijII',
    appId: '1:758650158262:ios:8b636dc4fd6b3d451ffa17',
    messagingSenderId: '758650158262',
    projectId: 'uas-iot-7b202',
    storageBucket: 'uas-iot-7b202.firebasestorage.app',
    iosBundleId: 'com.example.uas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDPNsK3mW3hGeSh0TJ6lyPbjQ1YLxWTrA',
    appId: '1:758650158262:web:135418e525756f9d1ffa17',
    messagingSenderId: '758650158262',
    projectId: 'uas-iot-7b202',
    authDomain: 'uas-iot-7b202.firebaseapp.com',
    storageBucket: 'uas-iot-7b202.firebasestorage.app',
    measurementId: 'G-GGDG6XM9GB',
  );
}
